#!/bin/bash
set -e

source $(dirname $0)/version

cd $(dirname $0)/../package

TAG=${TAG:-${VERSION}}
REPO=${REPO:-ibuildthecloud}

cp ../bin/metadata-ping .
docker build -t ${REPO}/metadata-ping:${TAG} .

echo Built ${REPO}/metadata-ping:${TAG}
